<?php

global $wpdb;
$table_contacts         = $wpdb->prefix . "ms_contacts";
$table_call_details     = $wpdb->prefix . "ms_call_details";

if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

if(isset($_FILES['file']) && isset($_REQUEST['import-file-submit']) && isset($_REQUEST['import-type'])){
    
    //print_r($_REQUEST);

    $uploadedfile = $_FILES['file'];
    $upload_overrides = array( 'test_form' => false );
    $csvfile = wp_handle_upload( $uploadedfile, $upload_overrides );
    
    if ( $csvfile && ! isset( $csvfile['error'] ) ) {

        $fp = fopen($csvfile['file'], "r");
        $header = fgetcsv($fp);

        if($_REQUEST['import-type'] == 'avoxi'){
            require_once plugin_dir_path(__FILE__). 'import/template-import-avoxi.php';
        } elseif ($_REQUEST['import-type'] == 'dynamic') {
            require_once plugin_dir_path(__FILE__). 'import/template-import-dynamic.php';
        }

    } else {
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $csvfile['error'];
    } 
    
} else require_once plugin_dir_path(__FILE__). 'import/template-upload-file.php';

?>
